spring:
  datasource:
    username: root
    password: '0228'
    url: jdbc:mysql://192.168.91.128:3306/glshoop_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.60.1:8848
        metadata:
          preserved.heart.beat.interval: 1000 #该实例在客户端上报心跳的间隔时间。（单位:毫秒）
          preserved.heart.beat.timeout: 3000 #该实例在不发送心跳后，从健康到不健康的时间。（单位:毫秒
          preserved.ip.delete.timeout: 3000 #该实例在不发送心跳后，被nacos下掉该实例的时间。（单位:毫

#    oss相关配置
    alicloud:
      access-key: LTAI5tFchf3nCZWskeU4gm2M
      secret-key: uW7xIp11Ui2tlOb5fm8hIXQtQ7Pb3P
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com

  application:
    name: glshoop-product

  #配置json格式化的日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #主键自增
      logic-delete-value: 1 #逻辑删除 未删除的值
      logic-not-delete-value: 0 #逻辑删除 已删除的值

server:
  port: 11000

logging:
  level:
    com.mmry.glshoop.product: debug

